import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
const poppings = Poppins({weight:['400','500','600','700','800','900'],subsets:['latin']})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppings.className,"bg-zuai-slate-100")}>
      <div className="hidden md: md:h-screen md:w-[52px] md:border-r-1 md:bg-white md:fixed md:top-0 md:left-0 md:flex-shrink-0">
        <Sidebar />
      </div>
      <div className="md:h-screen md:w-[52px] md:border-r-1 md:bg-white md:fixed md:top-0 md:left-0 md:flex-shrink-0">
        <Sidebar />
      </div>
        {children}</body>
    </html>
  );
}
