import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
const poppings = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          poppings.className,
          "flex flex-col md:flex-row bg-zuai-slate-100"
        )}
      >
        <Sidebar />
        <div className=" flex justify-center w-full grow md:ml-20 mt-10 md:mt-0 ml-0">
          {children}
        </div>
      </body>
    </html>
  );
}
